import * as cdk from 'aws-cdk-lib';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as ecr from 'aws-cdk-lib/aws-ecr';
import * as ecs from 'aws-cdk-lib/aws-ecs';
import * as elbv2 from 'aws-cdk-lib/aws-elasticloadbalancingv2';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as rds from 'aws-cdk-lib/aws-rds';
import * as servicediscovery from 'aws-cdk-lib/aws-servicediscovery';
import { Construct } from 'constructs';

export interface CatalogStackProps extends cdk.StackProps {
  /** The shared VPC from the NetworkStack. */
  readonly vpc: ec2.Vpc;
  /** The shared ECS cluster from the NetworkStack. */
  readonly cluster: ecs.Cluster;
  /** The ECS Service Connect namespace from the NetworkStack. */
  readonly serviceConnectNamespace: servicediscovery.INamespace;
  /** The ALB's HTTPS listener from the NetworkStack. */
  readonly httpsListener: elbv2.ApplicationListener;
  /** Catalog's ECR repository, created in the NetworkStack. */
  readonly repository: ecr.Repository;
}

export class CatalogStack extends cdk.Stack {
  /** ECR repository for Catalog container images. */
  public readonly repository: ecr.Repository;
  /** The Aurora Serverless v2 cluster backing the Catalog service. */
  public readonly cluster: rds.DatabaseCluster;
  /** The Fargate task definition for the Catalog service. */
  public readonly taskDefinition: ecs.FargateTaskDefinition;
  /** The task role used by the Catalog container. */
  public readonly taskRole: iam.Role;
  /** The execution role used by ECS for the Catalog task. */
  public readonly executionRole: iam.Role;
  /** The Fargate service running Catalog with Service Connect. */
  public readonly service: ecs.FargateService;

  constructor(scope: Construct, id: string, props: CatalogStackProps) {
    super(scope, id, props);

    const { vpc, cluster: ecsCluster, serviceConnectNamespace, httpsListener, repository } = props;

    this.repository = repository;

    // Aurora Serverless v2 (PostgreSQL) for the relational product data.
    // CDK generates and stores database credentials in Secrets Manager from
    // creation, so no password is ever set or hardcoded manually. The cluster
    // lives in the private subnets, unreachable from the internet.
    this.cluster = new rds.DatabaseCluster(this, 'AuroraCluster', {
      engine: rds.DatabaseClusterEngine.auroraPostgres({
        version: rds.AuroraPostgresEngineVersion.VER_16_11,
      }),
      vpc,
      writer: rds.ClusterInstance.serverlessV2('writer', {
        autoMinorVersionUpgrade: true,
      }),
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS },
      defaultDatabaseName: 'shopmesh',
    });

    // Database credentials live in Secrets Manager, auto-generated by CDK.
    const dbSecret = this.cluster.secret;
    if (!dbSecret) {
      throw new Error('Aurora cluster did not create a database secret');
    }

    // Least-privilege task role: only reads its database credentials.
    this.taskRole = new iam.Role(this, 'TaskRole', {
      assumedBy: new iam.ServicePrincipal('ecs-tasks.amazonaws.com'),
    });
    dbSecret.grantRead(this.taskRole);

    // Execution role for ECS to pull the image and push logs.
    this.executionRole = new iam.Role(this, 'ExecutionRole', {
      assumedBy: new iam.ServicePrincipal('ecs-tasks.amazonaws.com'),
    });
    this.repository.grantPull(this.executionRole);
    // Fargate injects the secret as an environment variable at task start
    // using the execution role, so it needs read access to the secret too.
    dbSecret.grantRead(this.executionRole);
    this.executionRole.addToPolicy(
      new iam.PolicyStatement({
        actions: ['logs:CreateLogStream', 'logs:PutLogEvents'],
        resources: ['*'],
      }),
    );

    this.taskDefinition = new ecs.FargateTaskDefinition(this, 'TaskDefinition', {
      family: 'catalog-service',
      cpu: 256,
      memoryLimitMiB: 512,
      taskRole: this.taskRole,
      executionRole: this.executionRole,
      runtimePlatform: {
        operatingSystemFamily: ecs.OperatingSystemFamily.LINUX,
        cpuArchitecture: ecs.CpuArchitecture.X86_64,
      },
    });

    this.taskDefinition.addContainer('App', {
      image: ecs.ContainerImage.fromEcrRepository(this.repository),
      portMappings: [{ name: 'app', containerPort: 3000 }],
      environment: {
        PORT: '3000',
        DB_NAME: 'shopmesh',
      },
      secrets: {
        DB_CREDENTIALS: ecs.Secret.fromSecretsManager(dbSecret),
      },
      logging: new ecs.AwsLogDriver({
        streamPrefix: 'catalog',
      }),
    });

    // The ECS service. Service Connect registers Catalog under the short name
    // `catalog` in the mesh namespace so other services can reach it at
    // http://catalog:3000, and fail over quickly if a task goes down.
    // An explicit security group lets us grant Aurora and Service Connect
    // access to exactly this group.
    const serviceSecurityGroup = new ec2.SecurityGroup(this, 'ServiceSecurityGroup', {
      vpc,
      description: 'Catalog service tasks',
    });

    this.service = new ecs.FargateService(this, 'Service', {
      cluster: ecsCluster,
      serviceName: 'catalog-service',
      taskDefinition: this.taskDefinition,
      circuitBreaker: {
        rollback: true,
      },
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS },
      assignPublicIp: false,
      securityGroups: [serviceSecurityGroup],
      serviceConnectConfiguration: {
        namespace: serviceConnectNamespace.namespaceName,
        services: [
          {
            portMappingName: 'app',
            dnsName: 'catalog',
            port: 3000,
            // Move the proxy off the container port: the ALB health check and
            // ALB traffic then reach the app directly on 3000, while Service
            // Connect clients reach the proxy on 13000.
            ingressPortOverride: 13000,
          },
        ],
      },
    });

    // Aurora clusters have no inbound rules by default; allow the Catalog
    // tasks to reach the writer on the PostgreSQL port.
    this.cluster.connections.allowFrom(
      serviceSecurityGroup,
      ec2.Port.tcp(5432),
      'Catalog tasks connecting to Aurora',
    );

    // Service Connect traffic from Cart is task-to-task inside the VPC, not
    // through the ALB, so Catalog must accept it on its app port directly.
    this.service.connections.allowFrom(
      ec2.Peer.ipv4(vpc.vpcCidrBlock),
      ec2.Port.tcp(3000),
      'Service Connect traffic from within the VPC',
    );
    // Cart's Service Connect proxy reaches Catalog's proxy on the ingress port.
    this.service.connections.allowFrom(
      ec2.Peer.ipv4(vpc.vpcCidrBlock),
      ec2.Port.tcp(13000),
      'Service Connect proxy ingress from within the VPC',
    );

    // The ALB target group routes /product* to the Catalog tasks, health-
    // checking them on /health.
    const targetGroup = new elbv2.ApplicationTargetGroup(this, 'TargetGroup', {
      vpc,
      port: 3000,
      protocol: elbv2.ApplicationProtocol.HTTP,
      targetType: elbv2.TargetType.IP,
      healthCheck: {
        path: '/health',
        healthyHttpCodes: '200',
      },
    });
    targetGroup.addTarget(this.service);

    // Create the listener rule in this stack (referencing the cross-stack
    // listener) rather than calling addTargetGroups on the listener. Setting
    // the rule's scope to this stack keeps it and its target group together,
    // avoiding a cross-stack dependency cycle with the network stack.
    new elbv2.ApplicationListenerRule(this, 'CatalogRule', {
      listener: httpsListener,
      priority: 10,
      conditions: [elbv2.ListenerCondition.pathPatterns(['/product*'])],
      targetGroups: [targetGroup],
    });

    // Independent auto scaling: Catalog can grow on CPU to 4 tasks, a higher
    // ceiling than Cart so the two services scale differently under load.
    const scaling = this.service.autoScaleTaskCount({ maxCapacity: 4, minCapacity: 1 });
    scaling.scaleOnCpuUtilization('CpuScaling', {
      targetUtilizationPercent: 70,
    });
  }
}