import * as cdk from 'aws-cdk-lib';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as ecr from 'aws-cdk-lib/aws-ecr';
import * as ecs from 'aws-cdk-lib/aws-ecs';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as rds from 'aws-cdk-lib/aws-rds';
import * as servicediscovery from 'aws-cdk-lib/aws-servicediscovery';
import { Construct } from 'constructs';

export interface CatalogStackProps extends cdk.StackProps {
  /** The shared VPC from the NetworkStack. */
  readonly vpc: ec2.Vpc;
  /** The shared ECS cluster from the NetworkStack. */
  readonly cluster: ecs.Cluster;
  /** The ECS Service Connect namespace from the NetworkStack. */
  readonly serviceConnectNamespace: servicediscovery.INamespace;
}

export class CatalogStack extends cdk.Stack {
  /** ECR repository for Catalog container images. */
  public readonly repository: ecr.Repository;
  /** The Aurora Serverless v2 cluster backing the Catalog service. */
  public readonly cluster: rds.DatabaseCluster;
  /** The Fargate task definition for the Catalog service. */
  public readonly taskDefinition: ecs.FargateTaskDefinition;
  /** The Fargate service running Catalog with Service Connect. */
  public readonly service: ecs.FargateService;

  constructor(scope: Construct, id: string, props: CatalogStackProps) {
    super(scope, id, props);

    const { vpc, cluster: ecsCluster, serviceConnectNamespace } = props;

    // Catalog's image registry. Image scanning on push checks for known
    // vulnerabilities the moment an image is uploaded, before it is deployed.
    this.repository = new ecr.Repository(this, 'Repository', {
      repositoryName: 'shopmesh-catalog',
      imageScanOnPush: true,
    });

    // Aurora Serverless v2 (PostgreSQL) for the relational product data.
    // CDK generates and stores database credentials in Secrets Manager from
    // creation, so no password is ever set or hardcoded manually. The cluster
    // lives in the private subnets, unreachable from the internet.
    this.cluster = new rds.DatabaseCluster(this, 'AuroraCluster', {
      engine: rds.DatabaseClusterEngine.auroraPostgres({
        version: rds.AuroraPostgresEngineVersion.VER_16_11,
      }),
      vpc,
      writer: rds.ClusterInstance.serverlessV2('writer', {
        autoMinorVersionUpgrade: true,
      }),
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS },
    });

    // Database credentials live in Secrets Manager, auto-generated by CDK.
    const dbSecret = this.cluster.secret;
    if (!dbSecret) {
      throw new Error('Aurora cluster did not create a database secret');
    }

    // Least-privilege task role: only reads its database credentials.
    const taskRole = new iam.Role(this, 'TaskRole', {
      assumedBy: new iam.ServicePrincipal('ecs-tasks.amazonaws.com'),
    });
    dbSecret.grantRead(taskRole);

    // Execution role for ECS to pull the image and push logs.
    const executionRole = new iam.Role(this, 'ExecutionRole', {
      assumedBy: new iam.ServicePrincipal('ecs-tasks.amazonaws.com'),
    });
    this.repository.grantPull(executionRole);
    executionRole.addToPolicy(
      new iam.PolicyStatement({
        actions: ['logs:CreateLogStream', 'logs:PutLogEvents'],
        resources: ['*'],
      }),
    );

    this.taskDefinition = new ecs.FargateTaskDefinition(this, 'TaskDefinition', {
      cpu: 256,
      memoryLimitMiB: 512,
      taskRole,
      executionRole,
      runtimePlatform: {
        operatingSystemFamily: ecs.OperatingSystemFamily.LINUX,
        cpuArchitecture: ecs.CpuArchitecture.X86_64,
      },
    });

    this.taskDefinition.addContainer('App', {
      image: ecs.ContainerImage.fromEcrRepository(this.repository),
      portMappings: [{ name: 'app', containerPort: 3000 }],
      environment: {
        PORT: '3000',
      },
    });

    // The ECS service. Service Connect registers Catalog under the short name
    // `catalog` in the mesh namespace so other services can reach it at
    // http://catalog:3000, and fail over quickly if a task goes down.
    this.service = new ecs.FargateService(this, 'Service', {
      cluster: ecsCluster,
      taskDefinition: this.taskDefinition,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_WITH_EGRESS },
      assignPublicIp: false,
      serviceConnectConfiguration: {
        namespace: serviceConnectNamespace.namespaceName,
        services: [
          {
            portMappingName: 'app',
            dnsName: 'catalog',
            port: 3000,
          },
        ],
      },
    });
  }
}